class_name ActorLayerKit
extends Resource

## Packed per-layer art for one actor.
##
## The field atlas stacks `ActorLayerIds.FIELD_LAYER_ORDER` vertically, one full
## direction/frame sheet per layer (4 idle + 8 walk). The doll atlas stacks
## `ActorLayerIds.DOLL_LAYER_ORDER` horizontally. Hair styles are a separate
## stacked atlas whose IDs must match `AppearanceCatalog`. Generated by
## `tools/generate_mara_layers.ps1`.

@export var actor_id: StringName = &""
@export var field_atlas: Texture2D
@export var doll_atlas: Texture2D
@export var hair_field_atlas: Texture2D
@export var hair_doll_atlas: Texture2D
@export var hair_style_ids: Array[StringName] = [
	&"hair.crop",
	&"hair.fringe",
	&"hair.tousle",
]
@export var frame_width: int = 48
@export var frame_height: int = 64
@export var columns: int = 12
@export var rows: int = 5
@export var doll_frame_width: int = 96
@export var doll_frame_height: int = 128


func field_sheet_size() -> Vector2i:
	return Vector2i(frame_width * columns, frame_height * rows)


func doll_frame_size() -> Vector2i:
	return Vector2i(doll_frame_width, doll_frame_height)


func field_layer_region(layer_index: int) -> Rect2i:
	var sheet: Vector2i = field_sheet_size()
	return Rect2i(Vector2i(0, layer_index * sheet.y), sheet)


func doll_layer_region(layer_index: int) -> Rect2i:
	return Rect2i(Vector2i(layer_index * doll_frame_width, 0), doll_frame_size())


func hair_style_count() -> int:
	return hair_style_ids.size()


func hair_style_index(style_id: StringName) -> int:
	return hair_style_ids.find(style_id)


func hair_field_region(style_index: int) -> Rect2i:
	var sheet: Vector2i = field_sheet_size()
	return Rect2i(Vector2i(0, style_index * sheet.y), sheet)


func hair_doll_region(style_index: int) -> Rect2i:
	return Rect2i(Vector2i(style_index * doll_frame_width, 0), doll_frame_size())


func frame_cell(column: int, row: int) -> Rect2i:
	return Rect2i(Vector2i(column * frame_width, row * frame_height), Vector2i(frame_width, frame_height))


func validate_definition() -> Array[String]:
	var errors: Array[String] = []
	if String(actor_id).is_empty():
		errors.append("Actor layer kit is missing an actor ID.")
	if field_atlas == null:
		errors.append("Actor layer kit '%s' is missing its field atlas." % actor_id)
	if doll_atlas == null:
		errors.append("Actor layer kit '%s' is missing its doll atlas." % actor_id)
	var sheet: Vector2i = field_sheet_size()
	if field_atlas != null:
		var expected_field: Vector2i = Vector2i(sheet.x, sheet.y * ActorLayerIds.field_layer_count())
		if field_atlas.get_size() != Vector2(expected_field):
			errors.append(
				"Actor layer kit '%s' field atlas is %s; expected %s for %d layers." % [
					actor_id,
					field_atlas.get_size(),
					expected_field,
					ActorLayerIds.field_layer_count(),
				]
			)
	if doll_atlas != null:
		var expected_doll: Vector2i = Vector2i(
			doll_frame_width * ActorLayerIds.doll_layer_count(),
			doll_frame_height
		)
		if doll_atlas.get_size() != Vector2(expected_doll):
			errors.append(
				"Actor layer kit '%s' doll atlas is %s; expected %s for %d layers." % [
					actor_id,
					doll_atlas.get_size(),
					expected_doll,
					ActorLayerIds.doll_layer_count(),
				]
			)
	if hair_style_ids.size() != AppearanceCatalog.HAIR_STYLE_ORDER.size():
		errors.append("Actor layer kit '%s' hair styles must match AppearanceCatalog." % actor_id)
	else:
		for style_index: int in hair_style_ids.size():
			if hair_style_ids[style_index] != AppearanceCatalog.HAIR_STYLE_ORDER[style_index]:
				errors.append("Actor layer kit '%s' hair styles must match AppearanceCatalog." % actor_id)
				break
	if hair_field_atlas == null:
		errors.append("Actor layer kit '%s' is missing its hair field atlas." % actor_id)
	if hair_doll_atlas == null:
		errors.append("Actor layer kit '%s' is missing its hair doll atlas." % actor_id)
	if hair_field_atlas != null:
		var expected_hair_field: Vector2i = Vector2i(sheet.x, sheet.y * hair_style_count())
		if hair_field_atlas.get_size() != Vector2(expected_hair_field):
			errors.append(
				"Actor layer kit '%s' hair field atlas is %s; expected %s for %d styles." % [
					actor_id,
					hair_field_atlas.get_size(),
					expected_hair_field,
					hair_style_count(),
				]
			)
	if hair_doll_atlas != null:
		var expected_hair_doll: Vector2i = Vector2i(
			doll_frame_width * hair_style_count(),
			doll_frame_height
		)
		if hair_doll_atlas.get_size() != Vector2(expected_hair_doll):
			errors.append(
				"Actor layer kit '%s' hair doll atlas is %s; expected %s for %d styles." % [
					actor_id,
					hair_doll_atlas.get_size(),
					expected_hair_doll,
					hair_style_count(),
				]
			)
	if columns != SpriteSheetPlayback.IDLE_FRAME_COUNT + SpriteSheetPlayback.WALK_FRAME_COUNT:
		errors.append(
			"Actor layer kit '%s' must pack %d idle and %d walk columns." % [
				actor_id,
				SpriteSheetPlayback.IDLE_FRAME_COUNT,
				SpriteSheetPlayback.WALK_FRAME_COUNT,
			]
		)
	return errors
